# if coreutils is installed place it at front of the path so 
# those tools are found before darwins bsd based versions
if [ -d "/opt/homebrew/opt/coreutils/libexec/gnubin" ]
then
  PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
fi

# '[' -> '../../bin/g['
#  b2sum -> ../../bin/gb2sum
#  base32 -> ../../bin/gbase32
#  base64 -> ../../bin/gbase64
#  basename -> ../../bin/gbasename
#  basenc -> ../../bin/gbasenc
#  cat -> ../../bin/gcat
#  chgrp -> ../../bin/gchgrp
#  chmod -> ../../bin/gchmod
#  chown -> ../../bin/gchown
#  chroot -> ../../bin/gchroot
#  cksum -> ../../bin/gcksum
#  comm -> ../../bin/gcomm
#  cp -> ../../bin/gcp
#  csplit -> ../../bin/gcsplit
#  cut -> ../../bin/gcut
#  date -> ../../bin/gdate
#  dd -> ../../bin/gdd
#  df -> ../../bin/gdf
#  dir -> ../../bin/gdir
#  dircolors -> ../../bin/gdircolors
#  dirname -> ../../bin/gdirname
#  du -> ../../bin/gdu
#  echo -> ../../bin/gecho
#  env -> ../../bin/genv
#  expand -> ../../bin/gexpand
#  expr -> ../../bin/gexpr
#  factor -> ../../bin/gfactor
#  false -> ../../bin/gfalse
#  fmt -> ../../bin/gfmt
#  fold -> ../../bin/gfold
#  groups -> ../../bin/ggroups
#  head -> ../../bin/ghead
#  hostid -> ../../bin/ghostid
#  id -> ../../bin/gid
#  install -> ../../bin/ginstall
#  join -> ../../bin/gjoin
#  kill -> ../../bin/gkill
#  link -> ../../bin/glink
#  ln -> ../../bin/gln
#  logname -> ../../bin/glogname
#  ls -> ../../bin/gls
#  man -> ../gnuman
#  md5sum -> ../../bin/gmd5sum
#  mkdir -> ../../bin/gmkdir
#  mkfifo -> ../../bin/gmkfifo
#  mknod -> ../../bin/gmknod
#  mktemp -> ../../bin/gmktemp
#  mv -> ../../bin/gmv
#  nice -> ../../bin/gnice
#  nl -> ../../bin/gnl
#  nohup -> ../../bin/gnohup
#  nproc -> ../../bin/gnproc
#  numfmt -> ../../bin/gnumfmt
#  od -> ../../bin/god
#  paste -> ../../bin/gpaste
#  pathchk -> ../../bin/gpathchk
#  pinky -> ../../bin/gpinky
#  pr -> ../../bin/gpr
#  printenv -> ../../bin/gprintenv
#  printf -> ../../bin/gprintf
#  ptx -> ../../bin/gptx
#  pwd -> ../../bin/gpwd
#  readlink -> ../../bin/greadlink
#  realpath -> ../../bin/grealpath
#  rm -> ../../bin/grm
#  rmdir -> ../../bin/grmdir
#  seq -> ../../bin/gseq
#  sha1sum -> ../../bin/gsha1sum
#  sha224sum -> ../../bin/gsha224sum
#  sha256sum -> ../../bin/gsha256sum
#  sha384sum -> ../../bin/gsha384sum
#  sha512sum -> ../../bin/gsha512sum
#  shred -> ../../bin/gshred
#  shuf -> ../../bin/gshuf
#  sleep -> ../../bin/gsleep
#  sort -> ../../bin/gsort
#  split -> ../../bin/gsplit
#  stat -> ../../bin/gstat
#  stdbuf -> ../../bin/gstdbuf
#  stty -> ../../bin/gstty
#  sum -> ../../bin/gsum
#  sync -> ../../bin/gsync
#  tac -> ../../bin/gtac
#  tail -> ../../bin/gtail
#  tee -> ../../bin/gtee
#  test -> ../../bin/gtest
#  timeout -> ../../bin/gtimeout
#  touch -> ../../bin/gtouch
#  tr -> ../../bin/gtr
#  true -> ../../bin/gtrue
#  truncate -> ../../bin/gtruncate
#  tsort -> ../../bin/gtsort
#  tty -> ../../bin/gtty
#  uname -> ../../bin/guname
#  unexpand -> ../../bin/gunexpand
#  uniq -> ../../bin/guniq
#  unlink -> ../../bin/gunlink
#  uptime -> ../../bin/guptime
#  users -> ../../bin/gusers
#  vdir -> ../../bin/gvdir
#  wc -> ../../bin/gwc
#  who -> ../../bin/gwho
#  whoami -> ../../bin/gwhoami
#  yes -> ../../bin/gyes