######
# tmux config
######

# configure tmux leader 
set -g prefix 'C- '
bind 'C- ' send-prefix
unbind C-b

# bind <leader>r to reload tmux config
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded tmux conf"

# use vim keybindings in copy mode
setw -g mode-keys vi

# use vim move keys to navigate splits
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
